version: '3.5'

services:
  nodejs:
    build: .
    command: sh -c "npm i && npm start"
    ports:
      - "8000:3333"
    volumes:
      - ./:/usr/src/app
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"



       